// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Aleena
package Assignment1;

/************************************************************/
/**
 * 
 */
public class Agent {
	/**
	 * 
	 */
	private int victoryPoints;
	/**
	 * 
	 */
	private Resources[] hand;
	/**
	 * 
	 */
	public String name;

	/**
	 * 
	 * @param resource 
	 */
	public void addResource(Resources resource) {
	}

	/**
	 * 
	 * @param resource 
	 */
	public void removeResource(Resources resource) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}

	/**
	 * 
	 * @param points 
	 */
	public void addVictoryPoints(int points) {
	}

	/**
	 * 
	 * @return 
	 */
	public String getName() {
	}
}
