// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Aleena
package Assignment1;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/************************************************************/
/**
 * 
 */
public class Agent {
	private int victoryPoints;
	private List<Resources> hand;
	private String name;

	public Agent (int victoryPoints, String name){
		this.victoryPoints = victoryPoints;
		this.hand = new ArrayList<>();
		this.name = name;
	}

	/**
	 * 
	 * @param resource 
	 */
	public void addResource(Resources resource) {
		hand.add(resource);
	}

	/**
	 * 
	 * @param resource 
	 */
	public void removeResource(Resources resource) {
        for (int i = 0; i < hand.size(); i++) {
            if (hand.get(i) == resource) {  
                hand.remove(i);
                break; 
            }
        }
    }

	/**
	 * 
	 * @return  
	 */
	public int getVictoryPoints() {
		return victoryPoints;

	}
	
	public String getName() {
		return name;
	}

	public int getHandSize() {
    	return hand.size();
	}

	public Resources getRandomResourceFromHand() {
    	if (hand.isEmpty()) return null;
    	return hand.get(new Random().nextInt(hand.size()));
	}

}
