// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Sara
package Assignment1;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 * @param Tile 
	 * @return 
	 */
	public Tile[] getTile(Tile[] Tile) {
	}

	/**
	 * 
	 * @param Edge 
	 * @return 
	 */
	public Edge[] getEdge(Edge Edge) {
	}

	/**
	 * 
	 * @param Node 
	 */
	public void getNode(Node[] Node) {
	}
}
