// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Sara
package Assignment1;

/************************************************************/

import java.util.*;

/**
 * 
 */
public class Board {
	/**
	 * 
	 * @param Tile 
	 * @return 
	 */
	private List<Edge> edges;
	private List<Node> nodes;
	private List<Tile> tiles;

	private Map<Node, Building> nodeBuildings;
	private Map<Edge, Road> edgeRoads;

	public Board(List<Tile> tiles, List<Edge> edges, List<Node> nodes) {
		this.tiles = tiles;
		this.edges = edges;
		this.nodes = nodes;
		this.nodeBuildings = new HashMap<Node, Building>();
		this.edgeRoads = new HashMap<Edge, Road>();

	}

	public Tile getTile(int index) {
		return tiles.get(index);
	}

	/**
	 * 
	 * @param index
	 * @return 
	 */
	public Edge getEdge(int index) {
		return edges.get(index);
	}

	/**
	 *
	 * @param index
	 */
	public Node getNode(int index) {
		return nodes.get(index);
	}

	public Building getBuildingAtNode(Node node) {
    	return nodeBuildings.get(node);
	}

	public Road getRoadAtEdge(Edge edge) {
    	return edgeRoads.get(edge);
	}

	public void placeSettlement(Node node, Building settlement) {
    	nodeBuildings.put(node, settlement);
	}

	public void placeCity(Node node, Building city, Agent agent) {
    	nodeBuildings.put(node, city);
	}

	public Map<Edge, Road> getEdgeRoads() {
    	return edgeRoads;
	}

	public List<Tile> getTiles() {
		return tiles;
	}

	public List<Node> getNodes() {
		return nodes;
	}

}
