// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Sara
package Assignment1;

/************************************************************/

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 
 */
public class Board {
	/**
	 * 
	 * @param Tile 
	 * @return 
	 */
	private List<Edge> edges;
	private List<Node> nodes;
	private List<Tile> tiles;

	private Map<Node, Building> nodeBuildings;
	private Map<Edge, Road> edgeRoads;

	public Board(List<Tile> tiles, List<Edge> edges, List<Node> nodes) {
		this.tiles = tiles;
		this.edges = edges;
		this.nodes = nodes;
		this.nodeBuildings = new HashMap<Node, Building>();
		this.edgeRoads = new HashMap<Edge, Road>();

	}

	public Tile getTile(int index) {
		return tiles.get(index);
	}

	/**
	 * 
	 * @param index
	 * @return 
	 */
	public Edge getEdge(int index) {
		return edges.get(index);
	}

	/**
	 *
	 * @param index
	 */
	public Node getNode(int index) {
		return nodes.get(index);
	}

	public String placeSettlement(Node node, Settlement settlement) {
		if(nodeBuildings.containsKey(node)) {
			return "There is already a settlement for this node!";
		}

		nodeBuildings.put(node, settlement);
		return "Settlement placed.";
	}
}
