// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Ashley 

package Assignment1;

/************************************************************/
/**
 * 
 */
public abstract class Building {
	/**
	 * keeps track of the which player owns this road
	 */
	private Agent owner;

	/**
	 * this will tell us how many victory points each building is worth
	 */
	private int victoryPoint;

	/**
	 * Constructor for the object creation
	 * @param owner
	 */
	public Building(Agent owner, int points) {
		this.owner = owner;
		this.victoryPoint = points;
	}

	/**
	 * This method will check if the input resourses are enough to buy the building
	 * @param resource 
	 * @return 
	 */
	public abstract boolean resourcePayment(Resources[] resource);

	/**
	 * getter method for owner of the building
	 * @return the owner of the building
	 */
	public Agent getAgent() {
		return this.owner;
	}

	/**
	 *
	 * @return what the building is worth in victory points
	 */
	public int getVictoryPoint(){
		return this.victoryPoint;
	}
}
