// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
//Ashley
package Assignment1;

/************************************************************/
/**
 * 
 */
public class City {
	/**
	 * 
	 */
	private int resourceMultiplier;

	/**
	 * 
	 * @param resources 
	 * @return 
	 */
	public boolean resourcePayment(Resources[] resources) {
	}
}
