// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Aleena 

package Assignment1;

public interface Dice {

	/**
	 * 
	 * @return 
	 */
	public int roll();
}


