// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Aleena 

package Assignment1;

public interface Dice {

	/**
	 * 
	 * @return Generates a random integer value representing a die roll.
	 */
	public int roll();
}


