// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private Node[] nodes;

	/**
	 * 
	 * @param node 
	 */
	public void Edge(Node[] node) {
	}

	/**
	 * 
	 * @return 
	 */
	public Node[] getNodes() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean hasRoad() {
	}
}
