// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Sara
package Assignment1;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private Node[] nodes;

	/**
	 * 
	 * @param node1
	 * @param node2
	 */
	public Edge(Node node1, Node node2) {
		this.nodes = new Node[2];
		this.nodes[0] = node1;
		this.nodes[1] = node2;
	}

	/**
	 * 
	 * @return 
	 */
	public Node[] getNodes() {
		return nodes;
	}
}
