	// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Aleena 
package Assignment1;

/************************************************************/
/**
 * 
 */
public class MultiDice {
	/**
	 * 
	 * @param die 
	 * @return 
	 */
	public int addDie(int die) {
	}
}
