// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Aleena 
package Assignment1;

import java.util.ArrayList;
import java.util.List;

public class MultiDice implements Dice {
	private final List<Dice> diceList;

	public MultiDice(){
		this.diceList = new ArrayList<>();
	}

	/**
	 * @param die 
	 * @return 
	 */

    public void addDice(Dice d) {
        diceList.add(d);
    }

        @Override
    public int roll() {
        int total = 0;

        for (Dice d : diceList) {
            total += d.roll();
        }

        return total;
    }
}

