// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Sara

package Assignment1;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int nodeID;

	/**
	 * 
	 * @return 
	 */
	public int getNodeNum() {
	}

	/**
	 * 
	 * @param nodeID 
	 */
	public void Node(int nodeID) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean hasBuilding() {
	}
}
