// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Sara

package Assignment1;

import java.util.ArrayList;
import java.util.List;

public class Node {
	
	private int nodeID;
	private List<Edge> connectedEdges; //Reference for navigation

	/**
	 * 
	 * @param nodeID 
	 */
	public Node(int nodeID) {
		this.nodeID = nodeID;
		this.connectedEdges = new ArrayList<>();
	}

	/**
	 *
	 * @return
	 */
	public int getNodeNum() {
		return nodeID;
	}

	/**
     * Required for the Distance Rule check in GamePlay.
     */
    public List<Node> getAdjacentNodes() {
        List<Node> neighbors = new ArrayList<>();
        for (Edge edge : connectedEdges) {
            for (Node otherNode : edge.getNodes()) {
                if (otherNode != this && !neighbors.contains(otherNode)) {
                    neighbors.add(otherNode);
                }
            }
        }
        return neighbors;
    }
    
    public void addEdge(Edge e) {
        this.connectedEdges.add(e);
    }

}
