// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Sara

package Assignment1;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int nodeID;

	/**
	 * 
	 * @param nodeID 
	 */
	public void Node(int nodeID) {
		this.nodeID = nodeID;
	}

	/**
	 *
	 * @return
	 */
	public int getNodeNum() {
		return nodeID;
	}
}
