// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Ashley 
package Assignment1;

/************************************************************/
/**
 * 
 */
public class Road extends Building{
	/**
	 * This keeps track of what edge has been used as a road
	 */
	private Edge edge;

	/**
	 * The constructor for the object
	 * @param owner the agent associated with this building
	 * @param edge the edge this road lies on
	 */
	public Road(Agent owner, Edge edge){
		super(owner, 0);
		this.edge = edge;
	}

	/**
	 * this method is for checking if the resources given are enough to pay for the road
	 * @param resources this is the array of resources being checked
	 * @return payment which describes if the correct payment was made
	 */
	@Override
	public boolean resourcePayment(Resources[] resources) {
		boolean payment = false;
		int lumber = 0;
		int brick = 0;
		for(Resources r : resources){
			switch (r){
				case LUMBER:
					lumber++;
					break;
				case BRICK:
					brick++;
					break;
				case ORE:
				case WOOL:
				case WHEAT:
				case NULL:
					return false;// should immediately terminate as none of these resources are part of the correct payment
			}
		}

		if(lumber == 1 && brick == 1){
			payment = true;
		}
		return payment;
	}
}
