// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Ashley 
package Assignment1;

/************************************************************/
/**
 * 
 */
public class Settlement extends Building{
	/**
	 * 
	 */
	private int resourceMultiplier;

	/**
	 * keeps track of the specific node this
	 */
	private Node node;

	/**
	 *
	 * @param owner the agent who owns the building
	 * @param node the node on which the building is sitting on
	 */
	public Settlement(Agent owner, Node node){
		super(owner, 1);
		this.node = node;
		this.resourceMultiplier = 1;
	}
	/**
	 * This method will tell if the correct payment is given to build a settlement
	 * @param resources array of resources given for payment
	 * @return payment
	 */
	@Override
	public boolean resourcePayment(Resources[] resources) {
		boolean payment = false;
		int wool = 0, brick = 0, wheat = 0, lumber = 0;
		for (Resources r : resources){
			switch (r){
				case WHEAT:
					wheat++;
					break;
				case WOOL:
					wool++;
					break;
				case BRICK:
					brick++;
					break;
				case LUMBER:
					lumber++;
					break;
				case NULL:
				case ORE:
					return false; // should immediately terminate as none of these resources are part of the correct payment
			}
		}

		if (wheat == 1 && wool == 1 && brick == 1 && lumber == 1){
			payment = true;
		}

		return payment;
	}

	/**
	 * This method tells the user how much this settlement is worth in victory points
	 * @return the resourse multiplier
	 */
	public int getResourceMultiplier() {
		return this.resourceMultiplier;
	}
}
