// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Sara

package Assignment1;

import java.util.ArrayList;
import java.util.List;

public class Tile {
	
	private Resources resource;
	private int rollValue;
	private int tilePosition;
	private List<Edge> edges;

	public Tile(Resources resource, int rollValue, int tilePosition, List<Edge> edges) {
		this.resource = resource;
		this.rollValue = rollValue;
		this.tilePosition = tilePosition;
		this.edges = edges;
	}

	public int getRollValue() {
		return rollValue;
	}

	/**
     * Required for GamePlay to know what card to give an Agent.
     */
	public Resources getResource() {
		return resource;
	}

	/**
     * Critical for GamePlay distribution logic. 
     * Navigates from the Tile -> its Edges -> the Nodes on those Edges.
     */
    public List<Node> getAdjacentNodes() {
        List<Node> adjacentNodes = new ArrayList<>();
        for (Edge edge : edges) {
            for (Node node : edge.getNodes()) {
                if (!adjacentNodes.contains(node)) {
                    adjacentNodes.add(node);
                }
            }
        }
        return adjacentNodes;
    }

}
