// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// Sara

package Assignment1;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private Resources resource;
	/**
	 * 
	 */
	private int rollValue;
	/**
	 * 
	 */
	private int tilePosition;
}
