// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public class GamePlay {
	/**
	 * 
	 */
	private int turnNumber;

	/**
	 * 
	 * @return 
	 */
	public int getTurnNumber() {
	}
}
