// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	private Edge edge;

	/**
	 * 
	 * @param resources 
	 * @return 
	 */
	public boolean resourcePayment(Resources[] resources) {
	}
}
